OpenOrchestra\BaseApiModelBundle\Document\ApiClient:
    properties:
        name:
            - NotBlank: ~
        trusted :
            - Type:
                type: bool
        blocked :
            - Type:
                type: bool
