parameters:
    open_orchestra_api.security.authentication_provider.oauth2.class: OpenOrchestra\BaseApi\Security\Authentication\Provider\OAuth2AuthenticationProvider
    open_orchestra_api.security.listener.oauth2.class: OpenOrchestra\BaseApi\Security\Firewall\OAuth2Listener

services:
    open_orchestra_api.security.authentication_provider.oauth2:
        class: %open_orchestra_api.security.authentication_provider.oauth2.class%
        arguments:
            - @open_orchestra_api.manager.access_token
    open_orchestra_api.security.listener.oauth2:
        class: %open_orchestra_api.security.listener.oauth2.class%
        arguments:
            - @security.token_storage
            - @security.authentication.manager
