parameters:
    open_orchestra_api.subscriber.serializer.class: OpenOrchestra\BaseApi\EventSubscriber\SerializerSubscriber
    open_orchestra_api.annotation_reader.class: Doctrine\Common\Annotations\AnnotationReader
    open_orchestra_api.subscriber.http_exception.class: OpenOrchestra\BaseApi\EventSubscriber\HttpExceptionSubscriber
    open_orchestra_api.context.group.class: OpenOrchestra\BaseApi\Context\GroupContext
    open_orchestra_api.subscriber.group_context.class: OpenOrchestra\BaseApi\EventSubscriber\GroupContextSubscriber
    open_orchestra_api.manager.access_token.class: OpenOrchestra\BaseApi\Manager\AccessTokenManager

services:
    open_orchestra_api.subscriber.serializer:
        class: %open_orchestra_api.subscriber.serializer.class%
        arguments:
            - @serializer
            - @annotation_reader
            - @controller_resolver
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_api.subscriber.http_exception:
        class: %open_orchestra_api.subscriber.http_exception.class%
        arguments:
            - %open_orchestra_api.controller.http_exception_controller%
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_api.context.group:
        class: %open_orchestra_api.context.group.class%
    open_orchestra_api.subscriber.group_context:
        class: %open_orchestra_api.subscriber.group_context.class%
        arguments:
            - @open_orchestra_api.context.group
            - @annotation_reader
            - @controller_resolver
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_api.manager.access_token:
        class: %open_orchestra_api.manager.access_token.class%
        arguments:
            - @open_orchestra_api.repository.access_token
            - @document_manager
            - %open_orchestra_api.document.access_token.class%
            - %open_orchestra_api.token.expiration_time%
