parameters:
    open_orchestra_api.transformer_manager.class: OpenOrchestra\BaseApi\Transformer\TransformerManager

services:
    open_orchestra_api.transformer_manager:
        class: %open_orchestra_api.transformer_manager.class%
        arguments:
            - @router
            - @open_orchestra_api.context.group
